from page import Page


def main():
    page = Page("Helios Nephrite EPL Invoice Detail Mock")
    page.add_frame()
    page.add_field("Interni cislo:")
    page.add_field("Cislo faktury:")
    page.add_frame()
    page.add_field("Typ dod.:")
    page.add_frame()
    page.add_field("Dodavatel:")
    page.add_field()
    page.add_frame()
    page.add_field("ICO:")
    page.add_frame()
    page.add_field("DIC:")
    page.add_field("DIC vlastni:")
    page.add_frame()
    page.add_field("Cislo uctu:")
    page.add_field()
    page.add_frame()
    page.add_field("Expozitura - dodavatel:")
    page.add_field()
    page.add_frame()
    page.add_field("Prijato:")
    page.add_field("DUZP:")
    page.add_field("Splatno:")
    page.add_field("Intrastat:")
    page.add_frame()
    page.add_field("Datum porizeni:")
    page.add_frame()
    page.add_field("Datum pripadu:")
    page.add_dropdown("Obdobi DPH:", "08", [f"{month:02}" for month in range(1, 13)])
    page.add_dropdown(selected="2023", options=[f"{year}" for year in range(2020, 2030)])
    page.add_checkbox("Dodatecne danove priznani:", False)
    page.add_frame()
    page.add_checkbox("Automaticke prepocitavani castek na formulari:", True)
    page.add_frame()
    page.add_checkbox("Mena:", False)
    page.add_field("Datum kurzu:")
    page.add_dropdown("Kod meny:", "", options=["", "CZK", "EUR", "PLN"])
    page.add_field()
    page.add_field()
    page.add_result()
    page.add_buttons()
    page.display()
    page.run_loop()


if __name__ == "__main__":
    main()
