{1}{1}25. 000
{136}{193}Previously on "Stargate SG-1":
{195}{299}You can't take down the entire NID,|and they'll kill you for trying.
{301}{415}You might be able to hold the evidence|over them and get Hammond reinstated.
{417}{516}- I'm not leavin' till I get what I came for.|- And what are you going to do?
{518}{602}Well, I was thinking about shootin' ya.
{604}{720}Kinsey's online activities connect him to|NID actions over the last year and a half.
{859}{973}Hell, you've been back in time,|forward in time. You've seen it all.
{975}{1041}I just wonder how things turn out.
{1043}{1158}I wonder how far you'd go to stop me|becoming president of the United States.
{1183}{1333}Advertise your product or brand here|contact www.OpenSubtitles.org today
{2597}{2647}Senator's been hit!
{4698}{4801}The assassination of Senator Kinsey has|sent shock waves through Washington.
{4803}{4873}With his party's convention|just weeks away,
{4875}{4948}the senator was considered|their most likely choice
{4950}{5039}for second spot on the presidential ticket.
{5055}{5113}Hey! I'm back.
{5115}{5169}What'd I miss?
{5171}{5251}Sir, Senator Kinsey is dead. He was shot.
{5290}{5386}- What?|- It's been all over the news for three days.
{5404}{5479}- I've been on vacation.|- It looks like a professional hit.
{5481}{5603}The shooter fired from a hotel room|across the street and then disappeared.
{5605}{5687}- Any suspects?|- Police aren't saying anything.
{5689}{5844}One can assume that a man in Senator|Kinsey's position will have many enemies.
{5846}{5883}Colonel.
{5913}{5955}General.
{5966}{6043}I'm sorry, but these men are here|to escort you to Peterson.
{6045}{6145}You'll be flown to Andrews and turned|over to the authorities in Washington.
{6147}{6183}Sir, what is this?
{6185}{6305}Colonel O'Neill is under arrest|for the murder of Senator Kinsey.
{6307}{6364}What?
{6426}{6523}- You'll have to come with us, sir.|- I don't think so.
{6525}{6594}- Colonel...|- General, I've been on vacation.
{6653}{6788}I believe you, Jack, but for the moment|we're going to have to cooperate.
{6958}{7057}- There's no way Colonel O'Neill did this.|- Yes, Major, but my hands are tied.
{7059}{7130}How could they think he did it?|He wasn't in Washington.
{7132}{7220}Actually, it looks like he was.
{7222}{7335}Major Davis is acting as liaison between|the Pentagon and the district attorney.
{7337}{7434}- He has a report for us. Major?|- Thank you, sir.
{7499}{7604}This is from a security camera in a hotel|across the street from the shooting,
{7606}{7688}just a couple of minutes after it happened.
{7763}{7876}The trajectory of the bullet indicates that|the shot did in fact come from this hotel.
{7878}{7940}- That doesn't prove anything.|- Based on this,
{7942}{8074}the FBI searched the colonel's house|and his cabin. They didn't find anything.
{8076}{8178}But a neighbour said they saw Colonel|O'Neill dumping something by the lake.
{8180}{8272}They sent down a diver,|who came up with this.
{8466}{8579}Ballistics match it with the bullet|that killed Senator Kinsey.
{8706}{8813}I don't know what to say, sir. It's no secret|there was bad blood between them.
{8815}{8920}Come on. They had a few run- ins.|That's hardly a motive for murder.
{8922}{9012}I've read the file on Kinsey,|but it is a little vague.
{9014}{9074}The senator was involved with individuals
{9076}{9166}who were unhappy with the way|Stargate Command was being run.
{9168}{9228}They tried to force|General Hammond to resign.
{9230}{9310}Colonel O'Neill connected|Kinsey to their illegal activities
{9312}{9394}and threatened to go public|unless he got them to back off.
{9396}{9476}So, technically,|Kinsey was protecting the SGC.
{9478}{9531}True, but he wasn't happy about it.
{9533}{9616}But that's not a motive to kill him.|It's a motive to keep him alive.
{9618}{9745}Unfortunately, we can divulge none of|this information to the civilian authorities.
{9747}{9824}Senator Kinsey was shot|in broad daylight on a public street,
{9826}{9873}in front of civilian witnesses.
{9875}{9938}If we tried to shift this to a military court,
{9940}{10011}it would be a disaster|for the current administration.
{10013}{10103}With respect, the current administration|owes a lot to the colonel.
{10105}{10166}I'm aware of that, Major,|as is the president.
{10168}{10270}Unfortunately, there's nothing|he can do for Colonel O'Neill at this time.
{10272}{10340}On the other hand, I'm not a politician,
{10342}{10411}which is why I'm suspending|SG-1's offworld duties
{10413}{10475}and assigning you|to get to the bottom of this.
{10477}{10554}The full resources of this command|are at your disposal.
{10556}{10631}- Thank you, sir.|- Dismissed.
{11158}{11208}Colonel.
{11263}{11308}How are you doin'?
{11310}{11444}I'm accused of a murder I didn't commit.|How do you think I'm doin'?
{11612}{11676}When are you being|transferred to Washington?
{11678}{11736}Couple of days.
{11738}{11802}General Hammond has suspended|our offworld duties
{11804}{11918}in order that we may|investigate this situation further.
{11920}{11986}Unfortunately, it's not going very well.
{11988}{12081}There is evidence that places you|at the scene of the shooting.
{12083}{12158}I was fishing.
{12223}{12301}Look, Kinsey wasn't exactly|my best buddy,
{12303}{12385}and on occasion I felt like|beating the crap out of him,
{12387}{12432}but I didn't kill him.
{12434}{12522}They somehow have a video
{12524}{12638}that clearly places you|in Washington DC three days ago.
{12640}{12696}I don't believe this.
{12698}{12778}We know you've been|on secret missions before.
{12780}{12901}I wasn't on a mission, Jonas.|I was in Minnesota, on vacation.
{12903}{12973}Did you encounter anyone|that can verify your story?
{12975}{13063}I was 20 miles away|from the closest town, alone.
{13065}{13113}That was the point.
{13190}{13274}Perhaps this is all|part of an elaborate plan.
{13276}{13423}Those responsible chose to act at a time|when they knew you would have no alibi.
{13493}{13611}I checked the video to see if it had been|doctored, but it appears to be genuine.
{13613}{13755}So either that really is Colonel O'Neill|or someone who looks exactly like him.
{13757}{13828}We have encountered|duplicating technology before.
{13830}{13935}I was thinking the same thing, but those|mimic devices are under heavy guard.
{13937}{13992}Mimic devices?
{14015}{14077}Someone wanna fill me in?
{14164}{14248}Three years ago, we had|a foothold situation here at the SGC.
{14250}{14316}Aliens gained control|by using mimic devices
{14318}{14420}to impersonate and then replace|base personnel, including myself.
{14422}{14518}- Why haven't I heard this before?|- Given the seriousness of the breach,
{14520}{14656}a decision was made to erase all mention|of the incident from official records.
{14658}{14767}- Where are these devices now?|- Area 51.
{14979}{15062}- How many do you have?|- We recovered 12 from the SGC.
{15064}{15114}They're all stored here.
{15116}{15256}- Has anyone studied them recently?|- We've all been focusing on the X- 303.
{15506}{15596}There we go.|All present and accounted for.
{15711}{15771}It's a fake.
{15816}{15906}All the mimic devices were switched.
{15908}{15967}Someone duplicated the duplicators?
{15969}{16087}The last test was six months ago. It could|have been taken any time after that.
{16089}{16181}There has got to be some way|that we can use this to clear you.
{16183}{16292}I don't think the alien- technology|defence is gonna fly.
{16294}{16365}If I understand this,|there is someone out there
{16367}{16459}that can make himself look exactly|like you. That's gotta be relevant.
{16461}{16548}It's classified information, Jonas.
{16596}{16698}But we can use it to find|the real assassin...maybe.
{16965}{17036}- So how do these things work?|- It's a two- part process.
{17038}{17104}First, you pass a person|through a scanning device,
{17106}{17185}which uploads their image|into a holographic sequencer.
{17187}{17237}- Which looks like this.|- Exactly.
{17239}{17295}Then you place that sequencer|on your body
{17297}{17382}and you instantly take on|the appearance of the person scanned.
{17384}{17479}- Was the scanning device taken?|- No, it's still at Area 51. We checked it.
{17481}{17552}So they can only impersonate|a limited number of people.
{17554}{17649}12, to be precise, including|Colonel O'Neill, Dr Fraiser and Daniel.
{17651}{17694}What about General Hammond?
{17696}{17778}The alien impersonating him|was trapped with several others.
{17780}{17904}They activated some kind of self- destruct|and blew themselves up.
{17906}{17983}In case you're wondering,|Teal'c and I were never scanned.
{17985}{18033}That's good to know.
{18035}{18139}I've requested all the personnel files on|those who had access to these devices.
{18141}{18200}I'd like the two of you to check them out.
{18202}{18284}- What about you?|- I'm going to Washington.
{18286}{18361}I need to look up an old acquaintance.
{18635}{18727}Major Carter.|I'm here to see Agent Barrett.
{18860}{18967}Major Carter. I was wondering|how long it would be before you came by.
{18969}{19037}Welcome to NID headquarters.
{19039}{19150}Only eight people at Area 51 have had|authorised access to the mimic devices.
{19152}{19246}- We must speak to them all.|- Most have moved to the X- 303 project,
{19248}{19312}so they're still living in Nevada.
{19332}{19407}Wait a minute. There's something.
{19409}{19459}Dr Brent Langham.
{19495}{19538}Deceased.
{19540}{19616}Killed in an automobile accident|three weeks ago.
{19618}{19740}Given the circumstance, that would seem|to be a highly unlikely coincidence.
{19804}{19868}What exactly are you|implying here, Major?
{19870}{19950}That the NID had a hand|in the assassination of a US senator?
{19952}{20059}Very few organisations have the|resources to pull off something like this.
{20061}{20126}And the man accused|happens to belong to one of them.
{20128}{20183}The SGC is not behind this.
{20213}{20306}Senator Kinsey was no friend|of the Stargate Command.
{20308}{20358}He tried to take you down more than once.
{20360}{20468}We don't engage in criminal activity,|Agent Barrett, unlike the NID.
{20470}{20561}The Prometheus incident was|orchestrated by a handful of rogue agents.
{20563}{20634}What about Steveston, Oregon?|You sat by and watched
{20636}{20710}while the Goa'uld took over|an entire town of civilians.
{20712}{20778}That was an officially|sanctioned operation.
{20780}{20837}It would've succeeded if it wasn't for you.
{20839}{20915}Are you kidding me?|Your agents were compromised
{20917}{21000}and your organisation|was about to be infiltrated.
{21002}{21047}Look, Major...
{21049}{21153}The videotape of Colonel O'Neill clearly|places him at the scene of the crime,
{21155}{21235}and the murder weapon|was found near his cabin.
{21237}{21310}So, if you'll excuse me...
{21427}{21477}I've got work to do.
{21956}{22006}It says here that by 2075
{22008}{22106}the Earth's oceans will be too warm|to sustain most coral reefs
{22108}{22200}and, once they're gone, the ecosystem|of the planet will collapse.
{22202}{22254}That's a cheerful thought.
{22256}{22353}We spend all of our time trying|to protect the world from the Goa'uld.
{22355}{22455}Maybe we should worry a little more|about protecting it from ourselves.
{22457}{22517}What are we doing out here,|Agent Barrett?
{22519}{22569}My office is bugged.
{22593}{22716}It's standard procedure to record|all conversations in NID headquarters.
{22718}{22817}What I'm about to say, Major, nobody else|can know, especially my superiors.
{22819}{22888}What are you talking about?
{22927}{23049}There's a cancer at the NID, a shadow|organisation that operates outside the law.
{23051}{23130}- It's time they were exposed.|- I agree.
{23132}{23197}The Prometheus incident|was the last straw.
{23199}{23273}I was called to the White House|for an assignment.
{23275}{23340}What does this have to do|with Colonel O'Neill?
{23342}{23402}Senator Kinsey was working for me.
{23404}{23506}He was about to give me enough evidence|to bring down the leadership of the group.
{23508}{23567}How did you convince him to do that?
{23569}{23660}I know about a few of the skeletons|in the senator's closet.
{23662}{23751}- And it is an election year.|- You blackmailed him.
{23753}{23842}I'll do whatever it takes|to bring these people down, Major.
{23956}{23991}Who else knows about this?
{23993}{24082}As of this moment, the president,|a few members of his staff, and you.
{24084}{24182}- You're working alone?|- The smaller the operation, the better.
{24184}{24269}You have no idea how far the corruption|goes. The SGC isn't immune.
{24271}{24329}You're taking a big risk talking to me.
{24331}{24403}I need your help.|And you haven't told me everything.
{24405}{24493}What makes you so sure|that Colonel O'Neill is innocent?
{24495}{24557}When you work with someone|that long, you know.
{24559}{24661}There's something more than that.|There's something you're not telling me.
{24663}{24765}Your job requires you to be suspicious|of everybody, even your co- workers.
{24767}{24843}Where I'm from, we trust each other|with our lives every day.
{24845}{24913}Maybe that's something|you can't understand.
{24915}{24988}I guess it's never too late to learn.
{25118}{25236}When the mimic devices were found, eight|scientists were assigned to study them.
{25238}{25314}The Pentagon hoped to adapt|the devices for use in the field.
{25316}{25447}However, while the holographic images|created by the aliens lasted indefinitely,
{25449}{25551}those created in the lab only lasted|for three to four minutes at a time,
{25553}{25622}due to problems with|electromagnetic interference.
{25624}{25722}So the project was scaled back, and five|of the team members were reassigned.
{25724}{25792}The remaining three were|Dr Singh, Dr Healey,
{25794}{25872}and this fellow - Dr Brent Langham.
{25874}{25953}They continued working for six months|with no breakthroughs.
{25955}{26009}Finally, the project was shut down.
{26011}{26095}Dr Healey and Dr Singh|were transferred to the X- 303 project.
{26097}{26134}And Dr Langham?
{26136}{26247}He was supposedly killed in a car crash|two days before the transfer was due.
{26249}{26330}The body was burned.|He was identified through dental records.
{26332}{26424}But the coroner missed something.|Toxicology report came back clean.
{26426}{26515}No signs of any drugs or alcohol|in the victim's blood.
{26517}{26605}- Why is that unusual?|- Dr Langham was epileptic.
{26607}{26690}His condition required regular doses|of anticonvulsant drugs.
{26692}{26755}There should have been|traces of those drugs.
{26757}{26826}The dental records were falsified.
{26828}{26905}The body recovered|at the crash site was someone else.
{26907}{26981}So you're saying this Dr Langham|took the mimic device
{26983}{27078}- and engineered his own disappearance.|- Or someone engineered it for him.
{27080}{27166}Are we suggesting, then,|that this scientist shot Kinsey?
{27168}{27229}I doubt it. He had|no paramilitary training.
{27231}{27319}Perhaps Dr Langham merely|provided the mimic devices for a fee.
{27321}{27391}But he can lead us|to whoever was responsible.
{27393}{27480}I don't care what it takes.|I want you to find this Dr Langham.
{27482}{27532}Yes, sir.
{27728}{27794}OK, what is this?
{27796}{27918}The rifle used to kill Senator Kinsey was|not one you pick up at your local store.
{27920}{27984}This is a one- stop shop|for unregistered weapons.
{27986}{28104}High- end goods, professional clientele.|There's a chance our shooter was here.
{28106}{28161}Why don't you shut them down?
{28163}{28228}I let them operate|in exchange for information.
{28230}{28334}Sometimes you gotta cross the line.|You just gotta know when to step back.
{28419}{28493}- Hey, Leo.|- Leo.
{28840}{28943}Agent Barrett. When are you gonna|get yourself a new suit?
{28945}{29048}- Black is good for any occasion.|- It's also thinning.
{29050}{29085}Who's your friend?
{29087}{29193}Major Samantha Carter,|United States Air Force.
{29195}{29255}We can talk in front of her.
{29330}{29368}What can I do for you?
{29370}{29445}We wanna know about a 700|with a customised breakdown stock.
{29447}{29520}Yeah. I moved one last week.
{29522}{29660}In all likelihood, the weapon you sold|was used to assassinate a US senator.
{29662}{29715}What's your point?
{29717}{29785}Was the buyer a regular customer?
{29787}{29849}No, I never seen him before.
{29893}{29966}- Is that the guy?|- That's the guy.
{30122}{30186}Did he look at any other weapons|besides the 700?
{30188}{30248}As a matter of fact, he did.
{30339}{30395}A sound- suppressed revolver rifle.
{30397}{30457}- Did he handle it?|- Sure.
{30459}{30535}- Was he wearing gloves?|- No.
{30551}{30654}- Has anybody handled it since?|- No, just Leo here.
{30723}{30773}How much?
{30944}{31013}There's one full set of prints|and one partial,
{31015}{31089}but neither of them match Colonel O'Neill.
{31091}{31151}It's a little strange.
{31153}{31203}Assuming the full set matches Leo,
{31205}{31271}that would mean the partial|belongs to the shooter.
{31273}{31371}- Maybe.|- It's the best lead we have.
{31373}{31438}The shooter probably|won't have a criminal record.
{31440}{31553}In fact, there's a good chance|he may not exist on any database at all.
{31555}{31630}Except maybe NID personnel files.
{31685}{31783}You said it yourself, Agent Barrett -|there's a cancer in your organisation.
{31785}{31855}Kinsey was gonna bring them down,|so they had him killed.
{31857}{31974}So did they hire an outside contractor|or use one of their own?
{32027}{32082}Give me the disk.
{32180}{32264}I'll check the files|and call you in a couple of hours.
{32427}{32489}Good call, checking for a second weapon.
{32491}{32553}- Thanks.|- You're welcome.
{32703}{32763}So where do we start?
{32815}{32889}It is probable that Dr Langham|has assumed a new identity.
{32891}{32966}New name, new address,|new social security number.
{32968}{33023}Can't change his medical condition.
{33025}{33104}Do not many thousands of people|suffer from this affliction?
{33106}{33180}Yes, but there's a wide|range of treatments.
{33182}{33291}Dr Langham was on specific drugs,|including primidone and carbamazepine.
{33293}{33388}So...we can access|the national pharmaceutical database
{33390}{33473}and focus on new prescriptions|written in the past three weeks.
{33475}{33533}We cross- reference that|with age and gender,
{33535}{33604}and we should be able|to narrow down the field.
{33760}{33867}- Have Teal'c and Jonas found anything?|- They have a lead on a missing scientist.
{33869}{33929}They think he may have|taken the mimic devices.
{33931}{34061}If the shooter was NID, we can track him|using the prints from the second rifle.
{34063}{34145}What about this Agent Barrett?|Are you sure you can trust him?
{34147}{34183}I think so.
{34185}{34301}You mustn't tell him about the foothold|incident. I shouldn't have even told Jonas.
{34303}{34363}I know, sir.|I'm hoping it won't come to that.
{34365}{34426}I'll keep you posted, sir.
{34428}{34483}- So?|- You were right.
{34485}{34571}The prints match|an NID agent named Mark Devlin.
{35017}{35110}- How'd you learn to drive?|- Daniel Jackson instructed me.
{35112}{35212}- When was that?|- I believe the year was 1969.
{35501}{35631}- Can I help you?|- We're looking for a Mr David Zwydel.
{35669}{35742}- That's me. What's this about?|- Our apologies.
{35744}{35862}- You are not the man we are looking for.|- Sorry, I must have made a mistake.
{35864}{35930}Have a good day.
{36018}{36105}- That guy look familiar to you?|- He did not.
{36107}{36156}Really?
{36158}{36219}He looked familiar to me.
{36221}{36264}No, wait, wait, wait.
{36266}{36316}I know that guy.
{36336}{36431}When I first came to Stargate Command,|he was an airman in the gate room.
{36433}{36483}I'm positive.
{36590}{36628}Mr Zwydel.
{36638}{36686}Mr Zwydel!
{36703}{36753}Around back.
{37301}{37351}Nice shot.
{37658}{37708}Dr Langham, I presume.
{37744}{37794}Indeed.
{37958}{38086}- You found Dr Langham.|- He's in a holding cell on level 16.
{38088}{38207}- Well done. Has he said anything?|- No, sir. But he did ask for a lawyer.
{38209}{38301}That could be a problem. We're not|following proper procedure here.
{38303}{38391}Sir, he stole top- secret material|and is an accessory to murder.
{38393}{38494}Dr Langham is also the only one that|can verify Colonel O'Neill's innocence.
{38496}{38580}Not necessarily. Major Carter|and Agent Barrett are pursuing a lead
{38582}{38647}that may take them to the real assassin.
{38649}{38716}- And if it doesn't?|- I know how you feel.
{38718}{38826}No one wants Colonel O'Neill back more|than I do, but this is a delicate situation.
{38828}{38943}I understand this man had some injuries|when you brought him in.
{39009}{39103}Dr Langham was reluctant|to accompany us back to the SGC.
{39105}{39205}- He required some convincing.|- All I'm saying is we have to be careful.
{39207}{39335}We're way outside our jurisdiction|and, like it or not, this man has rights.
{39337}{39449}He will volunteer the information.|Of that I am certain.
{40685}{40782}Look, this is a waste of time.|I got nothing to say.
{40943}{41082}OK, I took the mimic devices, but I didn't|know what they were planning to do.
{41173}{41308}What? You think I'm part of some kinda|murder conspiracy? Well, you're wrong.
{41558}{41703}All right, I'll tell you what I know,|but you have to promise me protection.
{42800}{42855}I'll get us in.
{43720}{43788}- What are you doing?|- Covering you.
{43790}{43854}Thank you. Get up.
{43856}{43902}Right.
{44075}{44148}When you switched the devices,|where'd you take them?
{44150}{44221}Washington. They wanted me|to take them myself,
{44223}{44304}because using a middleman|would be too risky.
{44306}{44399}- To whom are you referring?|- They call themselves the Committee.
{44401}{44452}They run the whole show.
{44454}{44514}We're going to need names.
{44563}{44612}This is conspiracy to commit murder.
{44614}{44697}I didn't know they'd use|the devices to kill anybody.
{44699}{44812}They told me they were gonna analyse the|technology for commercial applications.
{44814}{44884}Why would you believe that?
{44886}{44958}You don't think money|has anything to do with this?
{44960}{45092}In six months, there have been at least|ten new patents traceable to Area 51.
{45094}{45229}I'm talking industrial chemicals,|metallurgy, computers, you name it.
{45231}{45321}- So they're selling alien technology?|- No, they're buying it.
{45323}{45431}The members of the Committee aren't|secret agents, they're businessmen.
{45433}{45504}The rogue NID agents work for them.
{45506}{45587}They got millions invested|and they expect to make billions
{45589}{45709}by incorporating alien advancements|into their product lines.
{45711}{45759}This was about protecting the planet.
{45761}{45842}Nobody said it had to be|a non- profit business.
{45882}{45967}Give us the names|and we'll ensure your safety.
{45969}{46041}Well, I'm gonna need a few more details.
{46043}{46130}You work for the air force.|You don't have witness protection.
{46132}{46194}But we do have the Stargate.
{46217}{46311}- What do you mean?|- If these men are as powerful as you say,
{46313}{46387}there's probably nowhere|on Earth you'd be safe.
{46389}{46460}Fortunately, we have other options.
{46628}{46667}We need to talk.
{46669}{46755}Who else knows about|this operation at Stargate Command?
{46757}{46787}Why?
{46789}{46843}- We've got a leak, Major.|- Wait a minute.
{46845}{46930}Agent Devlin was waiting for us.|Somebody tipped him off.
{46932}{47006}Not necessarily. Think about it.
{47008}{47078}You used a computer|to access those personnel files.
{47080}{47132}Maybe somebody tracked you.
{47134}{47197}-|- Don't answer that.
{47199}{47286}- It's General Hammond.|- If they think we're dead, that's good.
{47288}{47345}You trust me, you trust my team.
{47372}{47427}Sir, what's happening?
{47454}{47509}Did he talk?
{47534}{47584}No, that's great news.
{47599}{47654}Yes, sir. Understood.
{47693}{47743}What is it?
{47761}{47855}We've got the names of those|responsible for the assassination.
{47857}{47934}- What's that supposed to mean?|- We have an inside source.
{47936}{47986}Who?
{48019}{48064}I can't.
{48066}{48126}This assignment|came from the White House.
{48128}{48230}If you don't tell me what I need to know,|I'm gonna have to make a phone call.
{48232}{48329}You're the one who's|always talking about trust.
{48506}{48618}The man who shot Kinsey|was using a piece of alien technology.
{48620}{48695}A device which creates|a flawless holographic disguise -
{48697}{48773}in this case, a duplicate image|of Colonel O'Neill.
{48775}{48849}It was a perfect plan to|get rid of Kinsey and the colonel.
{48851}{48980}Wait a minute. Why have I never|heard about this technology before?
{48982}{49108}We encountered the devices during|a foothold situation. It was a close one.
{49110}{49177}Kinsey wanted to shut down|the Stargate programme,
{49179}{49238}so it was covered up|by presidential order.
{49240}{49354}- Who's your source?|- A scientist at Area 51.
{49356}{49423}- He smuggled the devices out.|- That's not enough.
{49425}{49505}They're onto us. If we don't|move fast, they'll disappear.
{49507}{49589}We need more than one scientist|who made a deal for immunity.
{49591}{49656}That's all we have.
{49725}{49775}What?
{49793}{49861}Senator Kinsey's not dead.|He's in a coma.
{49863}{49949}- We've got him under 24- hour guard.|- Why didn't you tell me?
{49951}{50050}Because we needed to keep|his condition a secret for his protection.
{50052}{50182}If he recovers, he can provide us with the|information to bring these people down.
{50184}{50326}- So we were both keeping secrets.|- That's the way the game's played.
{50366}{50416}You've got a...
{50540}{50615}Anyway, the Pentagon's been informed.
{50617}{50675}They're sending a man to the hospital.
{50677}{50732}- Did I...?|- Close enough.
{50761}{50820}- Who are they sending?|- A liaison officer.
{50822}{50895}- Major Davis.|- Major Davis, yeah.
{50941}{50976}What?
{50978}{51080}There are 12 alien devices capable|of mimicking specific individuals.
{51082}{51154}Major Davis was one of them.
{51965}{52024}- Sergeant.|- Major Davis.
{52026}{52116}- I've come to check on the senator.|- Yes, sir.
{52775}{52875}- Agent Devlin, how did it go?|- Kinsey's dead.
{52877}{52961}Are you sure? He was supposed|to be dead the first time.
{52963}{53053}He wasn't wearing a bulletproof vest|this time. So, yeah, I'm sure.
{53055}{53140}There were a few complications, though.
{53316}{53416}- What's goin' on?|- Fire alarm. We need to move him.
{53526}{53587}We must ask you to wait here, sir.
{53589}{53644}Why is that, Sergeant?
{53751}{53811}Secondary casualties|are not our concern.
{53813}{53874}Major Davis can answer for those as well.
{53876}{53952}We still have a loose end.|They have Dr Langham in custody.
{53954}{54058}That's not important. His accusations|will be a minor inconvenience for us.
{54060}{54199}I suggest we use the mimic devices|to eliminate another thorn in our side.
{54201}{54282}- Someone at the SGC?|- General Hammond.
{54284}{54434}Once he's gone, we can replace him|with someone more sympathetic to us.
{55097}{55172}If they know about the devices,|they'll be prepared.
{55174}{55300}Devlin's right. Besides, now that|Kinsey's dead, we have other options.
{55302}{55380}I think it's time we sent someone|to talk to Hammond,
{55382}{55446}get him to reconsider|those retirement plans.
{55448}{55514}He doesn't seem like the type|to bow to pressure.
{55516}{55607}Well, then, we are going to|have to be very convincing.
{56197}{56312}Agent Devlin, I would like you|to pay General Hammond a visit.
{56314}{56453}Impress upon him our concerns for|the safety and wellbeing of his family.
{56455}{56531}If he still refuses to play ball?
{56533}{56583}Then kill him.
{56671}{56726}What is this?
{56768}{56835}General Hammond sends his regards.
{56867}{56937}Get your hands up. Come on, get'em up.
{57014}{57129}The hologram lasted six and a half|minutes. That's a new record for us.
{57258}{57330}- You took a big risk.|- I knew you were listening.
{57332}{57455}What makes you think I was gonna come|in before they incriminated themselves?
{57457}{57539}When you work with someone,|you just know.
{57801}{57866}Ah, Colonel O'Neill.
{57868}{57923}Glad you could make it.
{57965}{58003}What do you want, Kinsey?
{58005}{58097}I thought we should have a little chat|before we meet the press.
{58099}{58166}Did you need to gloat a little?
{58207}{58297}Don't be that way, Jack.|You need this as much as I do.
{58316}{58366}You'll only get public vindication
{58368}{58455}if the two of us appear|on the 6 o'clock news shaking hands.
{58457}{58520}Yeah. I'm not sure it's worth it.
{58582}{58701}The American people don't want their|air- force officers to be assassins, Jack.
{58703}{58760}They want them to be heroes.
{58780}{58842}I'm gonna make you a hero.
{58961}{59025}Shall we?
{59276}{59377}First of all, I want to apologise|to you and to the American people
{59379}{59486}for the deception|surrounding my untimely demise.
{59501}{59579}It was an unfortunate|but necessary final step
{59581}{59657}in my investigation|of certain antidemocratic forces
{59659}{59758}that had taken root|in several key government agencies.
{59760}{59899}The ringleaders of this conspiracy|have now been taken into custody.
{59901}{60030}Of course, taking a bullet was not part of|my original plan to bring these men down.
{60032}{60198}But the success of the operation was well|worth any personal sacrifice on my part.
{60200}{60306}And I want the American people|to know that, if elected,
{60308}{60415}I intend to bring that same determination
{60417}{60541}and zeal for justice|with me to the White House.
{60579}{60684}I would also like to thank Colonel|Jack O'Neill of the United States Air Force
{60686}{60772}for the vital role he played|in my investigation.
{60774}{60872}I can't go into details|for reasons of national security,
{60874}{60927}but I can assure you all
{60929}{61053}that any evidence pointing to the colonel|as my would- be assassin
{61055}{61133}was simply part of the operation.
{61198}{61250}Colonel.
{61537}{61637}Smile, Colonel.|You just won me the election.
{61911}{61959}Visiontext Subtitles: Sarah Emery
{63029}{63079}ENGLISH
{63104}{64604}Please rate this subtitle at www.osdb.link/3htu5|Help other users to choose the best subtitles
